/// FOR

for (let i = 0; i <= 10; i++) {
    // console.log(i);
    const j = 9
    console.log(i+"*"+j+"="+i*j);
    
    ;
    
}
let arr = [1,1,3,344,4]
for (let index = 0; index < arr.length; index++) {
    const element = arr[index];
    console.log(element);
        
}

// break and continue

for (let i = 0; i < 10; i++) {
    // const element = array[i];
    if (i ==5) {
        continue
        
    }

    console.log(`value of i is ${i}`);
    
    
}